Vagrant.configure("2") do |config|
  # Configuration for Ubuntu VM
  config.vm.define "AnsibleHost" do |ubuntu|
    ubuntu.vm.box = "generic/ubuntu1804"
    ubuntu.vm.hostname = "AnsibleHost"

    # Network
    ubuntu.vm.network "public_network", type: "hyperv", bridge: "External"
    #ubuntu.vm.network :forwarded_port, guest: 80, host: 8080

    # Shell script
    ubuntu.vm.provision "shell", path: "install-ansible.sh" 
    # Run as Hyper
    ubuntu.vm.provider "hyperv" do |hv|
      hv.vmname = "AnsibleHost"
      hv.cpus = 2
      hv.memory = 1024
    end
  end
  (1..3).each do |i|
    config.vm.define "vm#{i}" do |node|
      node.vm.box = "generic/ubuntu1804"  # Replace with the name of the base box you want to use
      node.vm.hostname = "vm#{i}"
      node.vm.network "public_network", type: "hyperv", bridge: "External"  # You can customize the network configuration as needed
      node.vm.provider "hyperv" do |hv|
        hv.vmname = "vm-AnsibleClient#{i}"
        hv.cpus = 2
        hv.memory = 1024  # Customize the amount of memory as needed
        # Assign a static IP address
        #hv.ip_address = "192.168.1.#{i + 50}"
      end
    end
  end
end
