Vagrant.configure("2") do |config|
    (1..5).each do |i|
      config.vm.define "vm#{i}" do |node|
        node.vm.box = "generic/ubuntu1804"  # Replace with the name of the base box you want to use
        node.vm.hostname = "vm#{i}"
        node.vm.network "public_network", type: "hyperv", bridge: "External"  # You can customize the network configuration as needed
        node.vm.provider "hyperv" do |hv|
          hv.vmname = "vm-Lab-Ansible#{i}"
          hv.cpus = 2
          hv.memory = 1024  # Customize the amount of memory as needed
          # Assign a static IP address
          #hv.ip_address = "192.168.1.#{i + 50}"
        end
      end
    end
  end
  